name: Deploy

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install deps
        run: npm install

      - name: Build
        run: npm run build

      - name: Save artifact
        uses: actions/upload-artifact@master
        with:
          name: stay-focused
          path: |
            ./
            !./node_modules
            !./.git
            !./.github 
            !./.src

  deploy:
    needs: [build]

    runs-on: ubuntu-latest

    steps:
      - name: Get artifact
        uses: actions/download-artifact@master
        with:
          name: stay-focused
          path: ./

      - name: Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          port: ${{ secrets.FTP_PORT }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: "./dist/"
          server-dir: "./html/focus/"
